name: citmatel_strawberry_dnd
description: Drag and drop module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 1.1.0-RELEASE.20220301

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  flutter_staggered_animations: ^1.0.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_animator: ^3.2.1
  dotted_border: ^2.0.0+2
  carousel_slider: ^4.0.0
  confetti: ^0.6.0
  tutorial_coach_mark: ^1.2.1
  decorated_icon: ^1.2.1
  fluttertoast: ^8.0.8
  sliver_fab:
    git:
      url: https://github.com/JesusHdezWaterloo/sliver_fab

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.4.0
  objectbox_flutter_libs: ^1.4.0
  flat_buffers: ^2.0.5
  clean_repo_objectbox: ^0.2.1-SNAPSHOT.20220223

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: ^1.4.0

flutter:
  assets:
    #Background
    - packages/citmatel_strawberry_dnd/assets/images/background.png

    #0 - Levels
    #TUTORIAL
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/3.png

    #6 - geografia
    #Level 1
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/6.png
    #Level 2
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/5.png
    #Level 3
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/6.png
    #Level 4
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/6.png
    #Level 5
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/5/6.png
    #Level 6
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/6/6.png
    #Level 7
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/7/5.png
    #Level 8
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/8/6.png
    #Level 9
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/9/6.png
    #Level 10
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/4.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/5.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/10/6.png
    #Level 11
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/11/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/11/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/11/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/11/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/11/4.png
    #Level 12
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/12/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/12/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/12/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/12/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/12/4.png
    #Level 13
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/13/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/13/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/13/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/13/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/13/4.png

  uses-material-design: true
