name: citmatel_strawberry_dnd
description: Drag and drop module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 0.0.1-SNAPSHOT.20211202

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.5.1
  clean_core: ^1.1.3-SNAPSHOT.20220109

  # Visual & Animations
  animations: ^2.0.2
  page_view_indicators: ^2.0.0
  flutter_svg: ^1.0.0
  flutter_staggered_animations: ^1.0.0
  photo_view: ^0.13.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^9.2.0
  flutter_spinkit: ^5.1.0
  flutter_animator: ^3.2.0
  cupertino_icons: ^1.0.2
  dotted_border: ^2.0.0+2
  carousel_slider: ^4.0.0
  confetti: ^0.6.0

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.3.0
  objectbox_flutter_libs: any
  clean_repo_objectbox: 0.1.2-SNAPSHOT.20220116

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - packages/citmatel_strawberry_dnd/assets/images/brain_in_blue.jpg
    - packages/citmatel_strawberry_dnd/assets/images/test.jpg
    - packages/citmatel_strawberry_dnd/assets/icons/frog.png
    - packages/citmatel_strawberry_dnd/assets/icons/bird.png
    - packages/citmatel_strawberry_dnd/assets/icons/deer.png
    - packages/citmatel_strawberry_dnd/assets/icons/monkey.png
    - packages/citmatel_strawberry_dnd/assets/icons/flower.png

  uses-material-design: true
