name: citmatel_strawberry_dnd
description: Drag and drop module for CITMATEL's 'strawberry' project

publish_to: "none"

version: 1.1.0-RELEASE.20220301

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.8.0"

dependencies:
  flutter:
    sdk: flutter

  # Architecture & Management
  get: ^4.6.1
  clean_core: ^1.2.3-RELEASE.20220206
  tuple: ^2.0.0

  # Visual & Animations
  flutter_staggered_animations: ^1.0.0
  flutter_fadein: ^2.0.0
  font_awesome_flutter: ^10.1.0
  flutter_animator: ^3.2.1
  dotted_border: ^2.0.0+2
  carousel_slider: ^4.0.0
  confetti: ^0.6.0
  tutorial_coach_mark: ^1.2.1
  decorated_icon: ^1.2.1
  fluttertoast: ^8.0.8
  sliver_fab:
    git:
      url: https://github.com/JesusHdezWaterloo/sliver_fab

  #Tools
  citmatel_strawberry_tools:
    path: ../citmatel_strawberry_tools

  #DB
  objectbox: ^1.4.0
  objectbox_flutter_libs: ^1.4.0
  flat_buffers: ^2.0.5
  clean_repo_objectbox:
    git:
      url: https://github.com/JesusHdezWaterloo/clean_repo_objectbox

dev_dependencies:
  flutter_test:
    sdk: flutter

  #flutter pub run dependency_validator
  dependency_validator: ^3.1.2

  #DB code generation
  build_runner: ^2.1.7
  objectbox_generator: ^1.4.0

flutter:
  assets:
    #Background
    - packages/citmatel_strawberry_dnd/assets/images/background.png

    #0 - Levels
    #TUTORIAL
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/0_tutorial/3.png

    #6 - geografia
    #Level 1
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/1/4.png
    #Level 2
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/2/4.png
    #Level 3
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/3/4.png
    #Level 4
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/bg.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/1.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/2.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/3.png
    - packages/citmatel_strawberry_dnd/assets/levels/6_geografia/4/4.png

  uses-material-design: true
